pull_request_rules:
  - name: automatic merge when CI passes
    conditions:
      - "status-success=CI"
      - "label=ready-to-merge"
    actions:
      merge:
        method: squash
        strict: smart
