name: "PR Triage"
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, locked]


permissions:
  pull-requests: write
  contents: read

jobs:
  assign-author:
    # uses: vyos/.github/.github/workflows/assign-author.yml@feature/T6349-reusable-workflows
    uses: solvers-camp/.github/.github/workflows/assign-author.yml@main
    secrets: inherit
