name: Check for unused imports using Pylint
on:
  pull_request:
    branches:
      - current

permissions:
  pull-requests: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-unused-imports:
    # uses: vyos/.github/.github/workflows/check-unused-imports.yml@current
    uses: solvers-camp/.github/.github/workflows/check-unused-imports.yml@main
    secrets: inherit

  add-pr-comment:
    needs: check-unused-imports
    runs-on: ubuntu-latest
    steps:
      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: |-
            ${{ needs.check-unused-imports.outputs.error_message == 'No issues in unused-imports' && '👍' || '❌' }}
            ${{ needs.check-unused-imports.outputs.error_message }}
          message-id: "UNUSED_IMPORTS_VALIDATION"
          allow-repeats: false
          refresh-message-position: true
