name: Check for unused imports using Pylint
on:
  pull_request:
    branches:
      - current

permissions:
  pull-requests: write
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # check-unused-imports:
  #   # uses: vyos/.github/.github/workflows/check-unused-imports.yml@current
  #   uses: solvers-camp/.github/.github/workflows/check-unused-imports.yml@main
  #   secrets: inherit

  add-pr-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message: HELLO
          message-id: "UNUSED_IMPORTS_VALIDATION"
          allow-repeats: false
          refresh-message-position: true
          repo-token: ${{ secrets.PAT_TOKEN }}
