name: Check for unused imports using Pylint
on:
  pull_request:
    branches:
      - current
    paths:
      # - '**'
      # - '!.github/**'
      # - '!**/*.md'
      - '**/*.py'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  check-unused-imports:
    #uses: vyos/.github/.github/workflows/check-unused-imports.yml@feature/T6349-reusable-workflows
    uses: solvers-camp/.github/.github/workflows/check-unused-imports.yml@main
    secrets: inherit
