name: Check for unused imports using Pylint
on:
  pull_request:
    branches:
      - current
      - sagitta
      - test-unused-import
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  check-unused-imports:
    #uses: vyos/.github/.github/workflows/check-unused-imports.yml@feature/T6349-reusable-workflows
    uses: solvers-camp/.github/.github/workflows/check-unused-imports.yml@main
    secrets: inherit
