---
    name: Check codeowners existence

    on:
        schedule:
        - cron: "0 0 * * *"
        workflow_dispatch:

    permissions:
      pull-requests: write
      contents: read

    jobs:
      check-codeowners-existence:
        # uses: vyos/.github/.github/workflows/check-pr-message.yml@feature/T6349-reusable-workflows
        uses: solvers-camp/.github/.github/workflows/check-codeowners-existence.yml@main
        secrets: inherit
