
name: "PR Conflicts checker"
on:
  pull_request_target:
    types: [synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  check-pr-conflict-call:
    # uses: vyos/.github/.github/workflows/check-pr-merge-conflict.yml@main
    uses: solvers-camp/.github/.github/workflows/check-pr-merge-conflict.yml@main
    # uses: vyos/.github/.github/workflows/check-pr-merge-conflict.yml@main
    secrets: inherit
