name: Cleanup feature branch after merge

on:
  pull_request:
    types: [closed]
    branches:
        - circinus

jobs:
  delete_branch:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'mirror/bp/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch=${{ github.event.pull_request.head.ref }}
          repo=${{ github.repository }}
          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          gh api -X DELETE "repos/${repo}/git/refs/heads/${branch}"
