name: Trigger-PR

on:
    pull_request_target:
      types:
        - closed
      branches:
        - current
        - circinus
    workflow_dispatch:

jobs:
  trigger-PR:
    # uses: vyos/.github/.github/workflows/trigger-pr.yml@current
    uses: solvers-camp/.github/.github/workflows/trigger-pr-using-diff.yml@main
    with:
      source_branch: 'current'
      target_branch: 'circinus'
    secrets:
      REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
      REMOTE_OWNER: ${{ secrets.REMOTE_OWNER }}
      PAT: ${{ secrets.PAT }}
