name: Trigger-PR

on:
    pull_request_target:
      types:
        - closed
      branches:
        - current
<<<<<<< HEAD
        - circinus
=======
>>>>>>> 1e945c4bd8e5f12395ce17aae3726af17c646680
    workflow_dispatch:

jobs:
  trigger-PR:
    # uses: vyos/.github/.github/workflows/trigger-pr.yml@current
    uses: solvers-camp/.github/.github/workflows/trigger-pr.yml@main
    with:
      source_branch: 'current'
      target_branch: 'circinus'
    secrets:
      REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
      REMOTE_OWNER: ${{ secrets.REMOTE_OWNER }}
      PAT: ${{ secrets.PAT }}
