name: Trigger-PR

on:
    pull_request_target:
      types:
        - closed
      branches:
        - current
    workflow_dispatch:

jobs:
  trigger-PR:
    # uses: vyos/.github/.github/workflows/trigger-pr.yml@current
    uses: solvers-camp/.github/.github/workflows/trigger-pr.yml@main
    secrets:
      REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
      REMOTE_OWNER: ${{ secrets.REMOTE_OWNER }}
      PAT: ${{ secrets.PAT }}
